language: node_js
node_js: stable
before_script:
  - npm cache clean --force
  - npm install 

script:
  - npm run build

# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key:
#       secure: $GITHUB_OAUTH_TOKEN
#   file: build/app/outputs/apk/app.apk 